### ISSUE TITLE
ResolutionException on Forge 37.0.29+

### ISSUE THREAD

**Issue by soir20** [shedaniel/architect-plugin#22]
Good afternoon.

I'm using the Architectury Plugin 3.3 snapshot to develop for 1.17 on IntelliJ IDEA 2021.2 (CE). I don't use the IntelliJ-specific plugin. When I use the `runClient` run configuration with Forge 37.0.29 or above, I receive a `ResolutionException`. For example:

```
Exception in thread "main" java.lang.module.ResolutionException: Modules minecraft.mapped.loom.mappings.layered.hash.LOL1024.v2forge and forge export package net.minecraftforge.energy to module examplemod
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:908)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:822)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:743)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:379)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:262)
```

I get a different exception every time I run it with different module and package names, but it's always a `ResolutionException` with the same stack trace.

The changelog for Forge 37.0.29 is `Bump BootStrapLauncher, and make sure Capability providers call parent revive.`. The related commit is [fcc8195](https://github.com/MinecraftForge/MinecraftForge/commit/fcc819584a658c82cd90550e83e6ff0750849fda).

## Solutions I've Tried ##
I've tried cleaning the project manually and with the Gradle tasks, re-importing the Gradle project, wiping my project and re-importing it from GitHub, invalidating caches through IntelliJ, and manually clearing my user `.gradle` folder to no avail.

Downgrading the Forge version to 37.0.28 or below resolves the problem.

I also searched GitHub to look for other repositories using the 3.3 plugin to see how they solved the problem, but nobody else appears to have tried using Forge 37.0.29+.

## Steps to Reproduce ##
I initially encountered this issue while developing my mod, but I was able to reproduce it on the example mod provided by Architectury. This makes me believe that the problem is within the plugin and not my own project.

1. Clone the [example mod repository](https://github.com/architectury/architectury-example-mod) and checkout the 1.17 branch.
2. Change the Forge version to 37.0.29 or above.
3. Generate run configurations with the `genIntelliJRuns` Gradle task.
4. Run `runClient` on the Forge subproject. A `ResolutionException` will appear after the mod files are discovered.
5. Downgrade the Forge version to 37.0.28, refresh the Gradle project, and `runClient` again. The game opens normally.

My mod doesn't use the Architectury API, and the issue still occurs.

**Comment by shedaniel** [comment]
Thanks! that helps to narrow down the issue to a specific commit.

**Comment by shedaniel** [comment]
Fixed, please refresh gradle via --refresh-dependencies, it would fetch the latest plugin versions.
