### ISSUE TITLE
`Cannot read field "outgoingEdges" because "handlerRangeBlock" is null` for reading classpath (by Architectury Transformer)

### ISSUE THREAD

**Issue by tanishisherewithhh** [shedaniel/architect-plugin#32]
Error:
```
java
[Architectury Transformer] Architectury Runtime 5.2.75
[Architectury Transformer] Read classpath in 1.658 s
Exception in thread "main" java.lang.NullPointerException: Cannot read field "outgoingEdges" because "handlerRangeBlock" is null
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1573)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1547)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at dev.architectury.transformer.shadowed.impl.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:451)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.toByteArray(SimpleTransformerHandler.java:231)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.applyTransforms(SimpleTransformerHandler.java:203)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.lambda$handle$1(SimpleTransformerHandler.java:80)
	at dev.architectury.transformer.input.FileView.lambda$handle$1(FileView.java:47)
	at dev.architectury.transformer.input.BaseFileAccess.handle(BaseFileAccess.java:82)
	at dev.architectury.transformer.input.FileView.handle(FileView.java:45)
	at dev.architectury.transformer.input.ForwardingFileView.handle(ForwardingFileView.java:47)
	at dev.architectury.transformer.input.ForwardingFileView.handle(ForwardingFileView.java:47)
	at dev.architectury.transformer.handler.SimpleTransformerHandler.handle(SimpleTransformerHandler.java:78)
	at dev.architectury.transformer.Transform.runTransformers(Transform.java:104)
	at dev.architectury.transformer.Transform.runTransformers(Transform.java:98)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:165)
```

Steps to reproduce:
- Use Minecraft Developement Plugin in JetBrains Intellj to create a new Architectury API mod.
- After the building is complete run any Minecraft Client loader.

Using:
- minecraft_version=`1.20.1`
- architectury_version=`9.1.10`
- fabric_loader_version=`0.14.21`
- fabric_api_version=`0.86.0+1.20.1`
- "architectury-plugin" version `3.4-SNAPSHOT`
- forge_version=`1.20.1-47.1.39`

**Comment by Juuxel** [comment]
Which version of Architectury Plugin are you using? Note that the Minecraft Development plugin tends to create outdated projects.

**Comment by tanishisherewithhh** [comment]
I believe I am using `1.6.3`, the latest version

**Comment by Juuxel** [comment]
Sorry if I was unclear, I meant the Gradle plugin known as "Architectury Plugin", not our IDEA plugin. The Gradle plugin manages the transformer.

**Comment by tanishisherewithhh** [comment]
I am extremely sorry, I misinterpreted it to IntelliJ plugin. I am currently using version - `3.4-SNAPSHOT`

**Comment by Redstoneguy129** [comment]
Any progress on this? I have the exact same error.

**Comment by AnAwesomGuy** [comment]
this happens when `@ExpectPlatform` methods have a body with like try-catches I think
