### ISSUE TITLE
runtime exception in TransformerRuntime.removeDuplicates

### ISSUE THREAD

**Issue by SammyForReal** [shedaniel/architect-plugin#50]
### Description

Whenever I start my forge client in dev env, The following exception gets thrown:

```
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 54
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
	at java.base/java.lang.String.substring(String.java:2709)
	at dev.architectury.transformer.TransformerRuntime.lambda$null$8(TransformerRuntime.java:250)
	at dev.architectury.transformer.input.BaseFileAccess.handle(BaseFileAccess.java:56)
	at dev.architectury.transformer.input.ForwardingFileView.handle(ForwardingFileView.java:42)
	at dev.architectury.transformer.TransformerRuntime.lambda$removeDuplicates$9(TransformerRuntime.java:246)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)
	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
	at dev.architectury.transformer.TransformerRuntime.removeDuplicates(TransformerRuntime.java:240)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:214)
```

### Context

It seems to be trying some String manipulation using the variable `relative`, which in my case contained the following string: `"dev\kleinbox\cccbridge\forge\InitializationForge.class"`

### Version

Architectury-Plugin: **3.4-SNAPSHOT**
Forge: **1.20.1-47.2.6**

**Comment by xp2-882030kgz010602** [comment]
I'm getting this issue too with this mod that uses Architectury as a dependency.
https://github.com/BlueStaggo/moderner-beta/tree/1.20.4

**Comment by forkiesassds** [comment]
Just forget about having lexforge 1.20.4 work in a dev env. I’ve tried, it just never works. Best might be to drop 1.20.4 and/or lexforge as nobody uses lexforge beyond 1.20.1

**Comment by xp2-882030kgz010602** [comment]
Re: 1.20.4: I should have made it clear that this isn't my mod. Additionally, I get the same error with the 1.21 version of that mod.
